"""empty message

Revision ID: 1227ec5eaf09
Revises: cacd93adf068
Create Date: 2021-09-21 15:06:42.834074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1227ec5eaf09'
down_revision = 'cacd93adf068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puesta_en_marcha', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_puesta_en_marcha_finished_at'), 'puesta_en_marcha', ['finished_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puesta_en_marcha_finished_at'), table_name='puesta_en_marcha')
    op.drop_column('puesta_en_marcha', 'finished_at')
    # ### end Alembic commands ###
