"""empty message

Revision ID: 1708e01a96de
Revises: c01047404d2c
Create Date: 2021-07-28 15:40:24.450891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1708e01a96de'
down_revision = 'c01047404d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oferta_licitacion_ibfk_3', 'oferta_licitacion', type_='foreignkey')
    op.create_foreign_key(None, 'oferta_licitacion', 'licitacion', ['licitacion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oferta_licitacion', type_='foreignkey')
    op.create_foreign_key('oferta_licitacion_ibfk_3', 'oferta_licitacion', 'licitacion', ['licitacion_id'], ['id'])
    # ### end Alembic commands ###
