"""empty message

Revision ID: 180320dfd457
Revises: c9ca25c161c1
Create Date: 2021-08-12 14:40:22.075219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180320dfd457'
down_revision = 'c9ca25c161c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_licitacion_created_at'), 'licitacion', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitacion_created_at'), table_name='licitacion')
    op.drop_column('licitacion', 'created_at')
    # ### end Alembic commands ###
