"""empty message

Revision ID: 2a670bc448e3
Revises: 52ee17e507a6
Create Date: 2021-08-12 10:00:32.682142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a670bc448e3'
down_revision = '52ee17e507a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacion_publica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['licitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licitacion_privada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['comprador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['licitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacion_privada_codigo'), 'licitacion_privada', ['codigo'], unique=True)
    op.add_column('licitacion', sa.Column('tipo', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licitacion', 'tipo')
    op.drop_index(op.f('ix_licitacion_privada_codigo'), table_name='licitacion_privada')
    op.drop_table('licitacion_privada')
    op.drop_table('licitacion_publica')
    # ### end Alembic commands ###
