"""empty message

Revision ID: 2fcea2ffe9ca
Revises: 
Create Date: 2021-07-30 14:19:17.101391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcea2ffe9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('telefono', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('telefono', 'user', ['telefono'], unique=False)
    # ### end Alembic commands ###
