"""empty message

Revision ID: 3d1e43907504
Revises: fcefb7756a36
Create Date: 2021-07-27 14:15:05.469185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1e43907504'
down_revision = 'fcefb7756a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comprador_ibfk_1', 'comprador', type_='foreignkey')
    op.create_foreign_key(None, 'comprador', 'user_role', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gestor_ibfk_1', 'gestor', type_='foreignkey')
    op.create_foreign_key(None, 'gestor', 'user_role', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('integrador_ibfk_1', 'integrador', type_='foreignkey')
    op.create_foreign_key(None, 'integrador', 'user_role', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_role_ibfk_1', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_ibfk_1', 'user_role', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'integrador', type_='foreignkey')
    op.create_foreign_key('integrador_ibfk_1', 'integrador', 'user_role', ['id'], ['id'])
    op.drop_constraint(None, 'gestor', type_='foreignkey')
    op.create_foreign_key('gestor_ibfk_1', 'gestor', 'user_role', ['id'], ['id'])
    op.drop_constraint(None, 'comprador', type_='foreignkey')
    op.create_foreign_key('comprador_ibfk_1', 'comprador', 'user_role', ['id'], ['id'])
    # ### end Alembic commands ###
