"""empty message

Revision ID: 4040e40eee5d
Revises: 9cc3100537ea
Create Date: 2021-07-28 15:14:27.470827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4040e40eee5d'
down_revision = '9cc3100537ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licitacion', 'kwp_inst',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
    op.alter_column('licitacion', 'kw',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
    op.alter_column('licitacion', 'cant',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
    op.drop_column('licitacion', 'descripcion')
    op.drop_column('licitacion', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion', sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False))
    op.add_column('licitacion', sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=False))
    op.alter_column('licitacion', 'cant',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
    op.alter_column('licitacion', 'kw',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
    op.alter_column('licitacion', 'kwp_inst',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
    # ### end Alembic commands ###
