"""empty message

Revision ID: 478a295a3fbc
Revises: ec0ca1d38ddd
Create Date: 2021-08-17 13:21:08.337278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478a295a3fbc'
down_revision = 'ec0ca1d38ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adquisicion_ibfk_1', 'adquisicion', type_='foreignkey')
    op.create_foreign_key(None, 'adquisicion', 'oferta_licitacion', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adquisicion', type_='foreignkey')
    op.create_foreign_key('adquisicion_ibfk_1', 'adquisicion', 'oferta_licitacion', ['id'], ['id'])
    # ### end Alembic commands ###
