"""se agrego usuario a oferta proveedor

Revision ID: 4b16a2857891
Revises: d35ddcebff8c
Create Date: 2021-07-22 09:31:07.188891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b16a2857891'
down_revision = 'd35ddcebff8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_proveedor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'oferta_proveedor', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oferta_proveedor', type_='foreignkey')
    op.drop_column('oferta_proveedor', 'user_id')
    # ### end Alembic commands ###
