"""empty message

Revision ID: 4c4fc68fd517
Revises: a8a554dc4bf2
Create Date: 2021-08-18 08:49:25.903577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4fc68fd517'
down_revision = 'a8a554dc4bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_solicitado', sa.String(length=30), nullable=False),
    sa.Column('aceptado', sa.Boolean(), nullable=True),
    sa.Column('fecha_peticion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pending_fecha_peticion'), 'user_pending', ['fecha_peticion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pending_fecha_peticion'), table_name='user_pending')
    op.drop_table('user_pending')
    # ### end Alembic commands ###
