"""empty message

Revision ID: 4d93fbe65d13
Revises: 
Create Date: 2021-08-10 09:32:32.573672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d93fbe65d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimensionamiento', sa.Column('proyecto_ejecutivo_key', sa.String(length=50), nullable=True))
    op.add_column('oferta_licitacion', sa.Column('kwp', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('oferta_licitacion', sa.Column('kw', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oferta_licitacion', 'kw')
    op.drop_column('oferta_licitacion', 'kwp')
    op.drop_column('dimensionamiento', 'proyecto_ejecutivo_key')
    # ### end Alembic commands ###
