"""tests

Revision ID: 4f6568262c61
Revises: c2fa6711164e
Create Date: 2021-07-09 17:14:24.358896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6568262c61'
down_revision = 'c2fa6711164e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    op.drop_table('engineer')
    op.drop_table('employee')
    # ### end Alembic commands ###
