"""empty message

Revision ID: 52ee17e507a6
Revises: 
Create Date: 2021-08-11 12:24:01.345176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52ee17e507a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('oferta_licitacion', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_licitacion', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('licitacion', 'status')
    # ### end Alembic commands ###
