"""se removio username de user

Revision ID: 5de98c4cd0ff
Revises: add4e05fc498
Create Date: 2021-07-23 15:02:18.659248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5de98c4cd0ff'
down_revision = 'add4e05fc498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
