"""empty message

Revision ID: 6eec5e67b886
Revises: 
Create Date: 2021-07-30 13:57:43.769932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eec5e67b886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('telefono', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('telefono', 'user', ['telefono'], unique=False)
    # ### end Alembic commands ###
