"""empty message

Revision ID: 6f9f394fc781
Revises: 886617bb7586
Create Date: 2021-08-16 14:10:14.807566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9f394fc781'
down_revision = '886617bb7586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adquisicion', sa.Column('integrador_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adquisicion', 'integrador', ['integrador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adquisicion', type_='foreignkey')
    op.drop_column('adquisicion', 'integrador_id')
    # ### end Alembic commands ###
