"""init

Revision ID: 8efdee8abdbe
Revises: 2b25f7e2dc12
Create Date: 2021-07-09 15:33:32.005934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8efdee8abdbe'
down_revision = '2b25f7e2dc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('nombre', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('apellidos', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('telefono', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['telefono'])
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'rol_id')
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'apellidos')
    op.drop_column('user', 'nombre')
    op.drop_table('rol')
    # ### end Alembic commands ###
