"""empty message

Revision ID: 957af7ea1138
Revises: 2fcea2ffe9ca
Create Date: 2021-08-03 11:59:12.147289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '957af7ea1138'
down_revision = '2fcea2ffe9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_grupo', sa.Column('integrador_id', sa.Integer(), nullable=False))
    op.drop_constraint('oferta_grupo_ibfk_1', 'oferta_grupo', type_='foreignkey')
    op.create_foreign_key(None, 'oferta_grupo', 'integrador', ['integrador_id'], ['id'])
    op.drop_column('oferta_grupo', 'user_id')
    op.add_column('oferta_proveedor', sa.Column('integrador_id', sa.Integer(), nullable=False))
    op.drop_constraint('oferta_proveedor_ibfk_3', 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key(None, 'oferta_proveedor', 'integrador', ['integrador_id'], ['id'])
    op.drop_column('oferta_proveedor', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_proveedor', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key('oferta_proveedor_ibfk_3', 'oferta_proveedor', 'user', ['user_id'], ['id'])
    op.drop_column('oferta_proveedor', 'integrador_id')
    op.add_column('oferta_grupo', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'oferta_grupo', type_='foreignkey')
    op.create_foreign_key('oferta_grupo_ibfk_1', 'oferta_grupo', 'user', ['user_id'], ['id'])
    op.drop_column('oferta_grupo', 'integrador_id')
    # ### end Alembic commands ###
