"""empty message

Revision ID: 9aa80d6892a0
Revises: b48110d1b05a
Create Date: 2021-09-20 22:07:25.939422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aa80d6892a0'
down_revision = 'b48110d1b05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adquisicion', sa.Column('oferta_prov_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'adquisicion', ['oferta_prov_id'])
    op.drop_constraint('adquisicion_ibfk_2', 'adquisicion', type_='foreignkey')
    op.create_foreign_key(None, 'adquisicion', 'oferta_proveedor', ['oferta_prov_id'], ['id'])
    op.drop_column('adquisicion', 'integrador_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adquisicion', sa.Column('integrador_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'adquisicion', type_='foreignkey')
    op.create_foreign_key('adquisicion_ibfk_2', 'adquisicion', 'integrador', ['integrador_id'], ['id'])
    op.drop_constraint(None, 'adquisicion', type_='unique')
    op.drop_column('adquisicion', 'oferta_prov_id')
    # ### end Alembic commands ###
