"""empty message

Revision ID: 9f7e358f0aaf
Revises: 05eaaf4c36cc
Create Date: 2021-07-12 09:02:44.527865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f7e358f0aaf'
down_revision = '05eaaf4c36cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kwh', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_condicionada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_1', sa.Integer(), nullable=False),
    sa.Column('oferta_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_1'], ['oferta_proveedor.id'], ),
    sa.ForeignKeyConstraint(['oferta_2'], ['oferta_proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_excluyente',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('oferta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['oferta_grupo.id'], ),
    sa.ForeignKeyConstraint(['oferta'], ['oferta_proveedor.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'oferta')
    )
    op.drop_table('marca_inversor')
    op.drop_table('marca_panel')
    op.drop_table('engineer')
    op.drop_table('manager')
    op.drop_table('employee')
    op.drop_constraint('inversor_ibfk_2', 'inversor', type_='foreignkey')
    op.drop_column('inversor', 'marca_id')
    op.add_column('oferta_proveedor', sa.Column('licitacion_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'oferta_proveedor', 'licitacion', ['licitacion_id'], ['id'])
    op.drop_constraint('panel_ibfk_2', 'panel', type_='foreignkey')
    op.drop_column('panel', 'marca_id')
    op.add_column('producto', sa.Column('marca_id', sa.Integer(), nullable=True))
    op.add_column('producto', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'producto', 'marca', ['marca_id'], ['id'])
    op.drop_column('producto', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.drop_column('producto', 'type')
    op.drop_column('producto', 'marca_id')
    op.add_column('panel', sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('panel_ibfk_2', 'panel', 'marca_panel', ['marca_id'], ['id'])
    op.drop_constraint(None, 'oferta_proveedor', type_='foreignkey')
    op.drop_column('oferta_proveedor', 'licitacion_id')
    op.add_column('inversor', sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('inversor_ibfk_2', 'inversor', 'marca_inversor', ['marca_id'], ['id'])
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('manager',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('manager_name', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employee.id'], name='manager_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('engineer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('engineer_name', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employee.id'], name='engineer_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marca_panel',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marca_inversor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('oferta_excluyente')
    op.drop_table('oferta_condicionada')
    op.drop_table('oferta_grupo')
    op.drop_table('licitacion')
    op.drop_table('marca')
    # ### end Alembic commands ###
