"""empty message

Revision ID: a0982a032af1
Revises: f1898632c09d
Create Date: 2021-08-12 10:57:35.838600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0982a032af1'
down_revision = 'f1898632c09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('licitacion_privada_ibfk_3', 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key(None, 'licitacion_privada', 'comprador', ['comprador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key('licitacion_privada_ibfk_3', 'licitacion_privada', 'comprador', ['comprador_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
