"""empty message

Revision ID: a51f7b761f9b
Revises: 6f9f394fc781
Create Date: 2021-08-16 15:30:54.448422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a51f7b761f9b'
down_revision = '6f9f394fc781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_proveedor', sa.Column('oferta_id', sa.Integer(), nullable=False))
    op.add_column('oferta_proveedor', sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=False))
    op.drop_constraint('oferta_proveedor_ibfk_2', 'oferta_proveedor', type_='foreignkey')
    op.drop_constraint('oferta_proveedor_ibfk_3', 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key(None, 'oferta_proveedor', 'oferta_licitacion', ['oferta_id'], ['id'])
    op.drop_column('oferta_proveedor', 'precio_unitario')
    op.drop_column('oferta_proveedor', 'producto_id')
    op.drop_column('oferta_proveedor', 'num_max')
    op.drop_column('oferta_proveedor', 'licitacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_proveedor', sa.Column('licitacion_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('oferta_proveedor', sa.Column('num_max', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('oferta_proveedor', sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('oferta_proveedor', sa.Column('precio_unitario', mysql.DECIMAL(precision=8, scale=2), nullable=False))
    op.drop_constraint(None, 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key('oferta_proveedor_ibfk_3', 'oferta_proveedor', 'producto', ['producto_id'], ['id'])
    op.create_foreign_key('oferta_proveedor_ibfk_2', 'oferta_proveedor', 'licitacion', ['licitacion_id'], ['id'])
    op.drop_column('oferta_proveedor', 'precio')
    op.drop_column('oferta_proveedor', 'oferta_id')
    # ### end Alembic commands ###
