"""empty message

Revision ID: a56a5cc40f2c
Revises: 3ddc45fe922b
Create Date: 2021-08-05 16:34:11.880713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56a5cc40f2c'
down_revision = '3ddc45fe922b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumo_json', sa.JSON(), nullable=False),
    sa.Column('ahorro_json', sa.JSON(), nullable=False),
    sa.Column('info_solar_json', sa.JSON(), nullable=False),
    sa.Column('rinv_inf_json', sa.JSON(), nullable=False),
    sa.Column('rinv_noinf_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumo_info_created_at'), 'consumo_info', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumo_info_created_at'), table_name='consumo_info')
    op.drop_table('consumo_info')
    # ### end Alembic commands ###
