"""empty message

Revision ID: a8a554dc4bf2
Revises: 478a295a3fbc
Create Date: 2021-08-17 13:23:54.931871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a554dc4bf2'
down_revision = '478a295a3fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adquisicion_ibfk_3', 'adquisicion', type_='foreignkey')
    op.create_foreign_key(None, 'adquisicion', 'oferta_licitacion', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adquisicion', type_='foreignkey')
    op.create_foreign_key('adquisicion_ibfk_3', 'adquisicion', 'oferta_licitacion', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
