"""empty message

Revision ID: a9a6691927ec
Revises: 2a670bc448e3
Create Date: 2021-08-12 10:05:31.000592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a6691927ec'
down_revision = '2a670bc448e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion_privada', sa.Column('comprador_id', sa.Integer(), nullable=False))
    op.drop_constraint('licitacion_privada_ibfk_1', 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key(None, 'licitacion_privada', 'comprador', ['comprador_id'], ['id'], ondelete='CASCADE')
    op.drop_column('licitacion_privada', 'creador_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion_privada', sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key('licitacion_privada_ibfk_1', 'licitacion_privada', 'comprador', ['creador_id'], ['id'], ondelete='CASCADE')
    op.drop_column('licitacion_privada', 'comprador_id')
    # ### end Alembic commands ###
