"""test

Revision ID: adbf922d0ee7
Revises: 4f6568262c61
Create Date: 2021-07-09 17:23:45.550685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbf922d0ee7'
down_revision = '4f6568262c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inversor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ficha_tecnica_key', sa.String(length=50), nullable=False),
    sa.Column('min_wp', sa.Integer(), nullable=False),
    sa.Column('max_wp', sa.Integer(), nullable=False),
    sa.Column('kw_ac', sa.Integer(), nullable=False),
    sa.Column('max_vdc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_isc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_imc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_mppt', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_mppt', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('num_mppt', sa.Integer(), nullable=False),
    sa.Column('strings', sa.Integer(), nullable=False),
    sa.Column('efc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca_inversor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('num_max', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ficha_tecnica_key', sa.String(length=50), nullable=False),
    sa.Column('wp', sa.Integer(), nullable=False),
    sa.Column('vmp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('imp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('efc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca_panel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel')
    op.drop_table('oferta_proveedor')
    op.drop_table('inversor')
    op.drop_table('producto')
    # ### end Alembic commands ###
