"""empty message

Revision ID: af97bc741734
Revises: 11185c8cdf4c
Create Date: 2021-08-20 13:36:56.131396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af97bc741734'
down_revision = '11185c8cdf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oferta_excluyente')
    op.drop_table('marca')
    op.drop_table('oferta_grupo')
    op.drop_table('oferta_condicionada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oferta_condicionada',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oferta_1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('oferta_2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['oferta_1'], ['oferta_proveedor.id'], name='oferta_condicionada_ibfk_1'),
    sa.ForeignKeyConstraint(['oferta_2'], ['oferta_proveedor.id'], name='oferta_condicionada_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oferta_grupo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integrador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integrador_id'], ['integrador.id'], name='oferta_grupo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marca',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oferta_excluyente',
    sa.Column('grupo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('oferta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['oferta_grupo.id'], name='oferta_excluyente_ibfk_1'),
    sa.ForeignKeyConstraint(['oferta'], ['oferta_proveedor.id'], name='oferta_excluyente_ibfk_2'),
    sa.PrimaryKeyConstraint('grupo_id', 'oferta'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
