"""empty message

Revision ID: b69c9b9611b8
Revises: 72f82be3ddda
Create Date: 2021-07-09 17:41:19.119546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b69c9b9611b8'
down_revision = '72f82be3ddda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('marca_inversor')
    op.drop_table('marca_panel')
    op.drop_constraint('inversor_ibfk_2', 'inversor', type_='foreignkey')
    op.drop_column('inversor', 'marca_id')
    op.drop_constraint('panel_ibfk_2', 'panel', type_='foreignkey')
    op.drop_column('panel', 'marca_id')
    op.add_column('producto', sa.Column('marca_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'producto', 'marca', ['marca_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.drop_column('producto', 'marca_id')
    op.add_column('panel', sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('panel_ibfk_2', 'panel', 'marca_panel', ['marca_id'], ['id'])
    op.add_column('inversor', sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('inversor_ibfk_2', 'inversor', 'marca_inversor', ['marca_id'], ['id'])
    op.create_table('marca_panel',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marca_inversor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('marca')
    # ### end Alembic commands ###
