"""se removio panel como foreign key de oferta_licitacion

Revision ID: b6f096413d1d
Revises: b7537776b6d7
Create Date: 2021-07-22 09:16:23.575774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6f096413d1d'
down_revision = 'b7537776b6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oferta_licitacion_ibfk_3', 'oferta_licitacion', type_='foreignkey')
    op.drop_column('oferta_licitacion', 'panel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_licitacion', sa.Column('panel_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('oferta_licitacion_ibfk_3', 'oferta_licitacion', 'panel', ['panel_id'], ['id'])
    # ### end Alembic commands ###
