"""se añadio tabla de oferta licitacion

Revision ID: b7537776b6d7
Revises: 5f5f8b9caffc
Create Date: 2021-07-22 08:46:29.124535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7537776b6d7'
down_revision = '5f5f8b9caffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oferta_licitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licitacion_id', sa.Integer(), nullable=True),
    sa.Column('comprador_id', sa.Integer(), nullable=True),
    sa.Column('min_kw', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_kw', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_wp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_wp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('precio_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitacion.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oferta_licitacion')
    # ### end Alembic commands ###
