"""empty message

Revision ID: b9fabb2969e4
Revises: b69c9b9611b8
Create Date: 2021-07-09 17:44:57.858839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fabb2969e4'
down_revision = 'b69c9b9611b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inversor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ficha_tecnica_key', sa.String(length=50), nullable=False),
    sa.Column('min_wp', sa.Integer(), nullable=False),
    sa.Column('max_wp', sa.Integer(), nullable=False),
    sa.Column('kw_ac', sa.Integer(), nullable=False),
    sa.Column('max_vdc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_isc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_imc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_mppt', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_mppt', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('num_mppt', sa.Integer(), nullable=False),
    sa.Column('strings', sa.Integer(), nullable=False),
    sa.Column('efc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('num_max', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ficha_tecnica_key', sa.String(length=50), nullable=False),
    sa.Column('wp', sa.Integer(), nullable=False),
    sa.Column('vmp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('imp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('efc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel')
    op.drop_table('oferta_proveedor')
    op.drop_table('inversor')
    op.drop_table('producto')
    op.drop_table('marca')
    # ### end Alembic commands ###
