"""empty message

Revision ID: c01047404d2c
Revises: 4040e40eee5d
Create Date: 2021-07-28 15:27:02.180758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c01047404d2c'
down_revision = '4040e40eee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oferta_licitacion', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_licitacion', sa.Column('tipo', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
