"""empty message

Revision ID: c014ac38478e
Revises: af97bc741734
Create Date: 2021-08-20 15:07:57.644853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c014ac38478e'
down_revision = 'af97bc741734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion', sa.Column('oferta_venta_asignada', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licitacion', 'oferta_venta_asignada')
    # ### end Alembic commands ###
