"""empty message

Revision ID: c04760fb4180
Revises: 180320dfd457
Create Date: 2021-08-13 09:28:59.951357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c04760fb4180'
down_revision = '180320dfd457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licitacion', 'status')
    op.add_column('oferta_licitacion', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oferta_licitacion', 'status')
    op.add_column('licitacion', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
