"""polymorphic association

Revision ID: c2fa6711164e
Revises: 4d81456897f2
Create Date: 2021-07-09 17:04:48.498777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fa6711164e'
down_revision = '4d81456897f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('tipo', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'tipo')
    # ### end Alembic commands ###
