"""empty message

Revision ID: cacd93adf068
Revises: 9aa80d6892a0
Create Date: 2021-09-21 09:56:05.634058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacd93adf068'
down_revision = '9aa80d6892a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instalacion', sa.Column('confirmacion_integrador', sa.Boolean(), nullable=False))
    op.add_column('instalacion', sa.Column('confirmacion_comprador', sa.Boolean(), nullable=False))
    op.add_column('instalacion', sa.Column('confirmacion_gestor', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instalacion', 'confirmacion_gestor')
    op.drop_column('instalacion', 'confirmacion_comprador')
    op.drop_column('instalacion', 'confirmacion_integrador')
    # ### end Alembic commands ###
