"""se removio usuario id de licitacion

Revision ID: d35ddcebff8c
Revises: b6f096413d1d
Create Date: 2021-07-22 09:20:38.721893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35ddcebff8c'
down_revision = 'b6f096413d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('licitacion_ibfk_1', 'licitacion', type_='foreignkey')
    op.drop_column('licitacion', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacion', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('licitacion_ibfk_1', 'licitacion', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
