"""empty message

Revision ID: d44212572c55
Revises: c04760fb4180
Create Date: 2021-08-13 09:48:25.417801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd44212572c55'
down_revision = 'c04760fb4180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_licitacion', sa.Column('aceptada', sa.Boolean(), nullable=False))
    op.drop_column('oferta_licitacion', 'activa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_licitacion', sa.Column('activa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('oferta_licitacion', 'aceptada')
    # ### end Alembic commands ###
