"""empty message

Revision ID: d76c2f21e659
Revises: 4d93fbe65d13
Create Date: 2021-08-10 09:44:52.602242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76c2f21e659'
down_revision = '4d93fbe65d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimensionamiento', sa.Column('status_comprador', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimensionamiento', 'status_comprador')
    # ### end Alembic commands ###
