"""empty message

Revision ID: e4ba0e45feef
Revises: 6aa39859057b
Create Date: 2021-08-05 11:52:09.642425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ba0e45feef'
down_revision = '6aa39859057b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumo_json', sa.JSON(), nullable=False),
    sa.Column('ahorro_json', sa.JSON(), nullable=False),
    sa.Column('info_solar_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo_info')
    # ### end Alembic commands ###
