"""empty message

Revision ID: ec0ca1d38ddd
Revises: a51f7b761f9b
Create Date: 2021-08-16 19:40:17.656051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec0ca1d38ddd'
down_revision = 'a51f7b761f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oferta_proveedor_ibfk_1', 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key(None, 'oferta_proveedor', 'integrador', ['integrador_id'], ['id'])
    op.drop_column('oferta_proveedor', 'licitacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oferta_proveedor', sa.Column('licitacion_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'oferta_proveedor', type_='foreignkey')
    op.create_foreign_key('oferta_proveedor_ibfk_1', 'oferta_proveedor', 'licitacion', ['licitacion_id'], ['id'])
    # ### end Alembic commands ###
