"""empty message

Revision ID: f1898632c09d
Revises: a9a6691927ec
Create Date: 2021-08-12 10:48:24.633513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1898632c09d'
down_revision = 'a9a6691927ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('licitacion_privada_ibfk_2', 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key(None, 'licitacion_privada', 'licitacion', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licitacion_privada', type_='foreignkey')
    op.create_foreign_key('licitacion_privada_ibfk_2', 'licitacion_privada', 'licitacion', ['id'], ['id'])
    # ### end Alembic commands ###
