"""empty message

Revision ID: ff89f9856d51
Revises: 3aace67f5b4a
Create Date: 2021-09-20 14:18:27.918286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff89f9856d51'
down_revision = '3aace67f5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adquisicion', sa.Column('oferta_prov_id', sa.Integer(), nullable=True))
    op.drop_constraint('adquisicion_ibfk_2', 'adquisicion', type_='foreignkey')
    op.create_foreign_key(None, 'adquisicion', 'oferta_proveedor', ['oferta_prov_id'], ['id'])
    op.drop_column('adquisicion', 'integrador_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adquisicion', sa.Column('integrador_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'adquisicion', type_='foreignkey')
    op.create_foreign_key('adquisicion_ibfk_2', 'adquisicion', 'integrador', ['integrador_id'], ['id'])
    op.drop_column('adquisicion', 'oferta_prov_id')
    # ### end Alembic commands ###
